### ISSUE TITLE
No such file or directory @ rb_sysopen - features. Please create a features directory to get started. (Errno::ENOENT)

### ISSUE THREAD

**Issue by seansparkman** [bitrise-steplib/steps-calabash-ios-uitest#5]
+------------------------------------------------------------------------------+
| (7) calabash-ios-uitest@0.9.1                                                |
+------------------------------------------------------------------------------+
| id: calabash-ios-uitest                                                      |
| version: 0.9.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2016-06-15T07:24:03-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Installing CFPropertyList 2.3.2
Installing awesome_print 1.6.1
Installing builder 3.2.2
Installing calabash-common 0.0.2
Using bundler 1.12.1
Installing diff-lcs 1.2.5
Installing multi_json 1.11.2
Installing multi_test 0.1.2
Installing edn 1.1.0
Installing geocoder 1.2.12
Installing httpclient 2.7.0.1
Installing json 1.8.3 with native extensions
Installing command_runner_ng 0.1.0
Installing retriable 2.0.2
Using thor 0.19.1
Using rack 1.6.4
Installing tilt 2.0.1
Installing gherkin 2.12.2 with native extensions
Installing run_loop 1.5.6
Using rack-protection 1.5.3
Installing cucumber 1.3.20
Installing sinatra 1.4.6
Installing slowhandcuke 0.0.3
Installing sim_launcher 0.4.13
Installing calabash-cucumber 0.16.4
Bundle complete! 1 Gemfile dependency, 25 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from slowhandcuke:

---
- To use the slowhandcuke formatter, simple add                 *
-   --format 'Slowhandcuke::Formatter'                          \* 
- to your cucumber.yml, Rakefile, or command line call          *
  *****************************************************************

========== Configs ==========
- features: 
- simulator_device: iPhone 6
- simulator_os: iOS 9.3
- simulator_UDID: 242C2D3D-4DB6-4811-8948-D23D2B2E9F09

=> run calabash test

cucumber
No such file or directory @ rb_sysopen - features. Please create a features directory to get started. (Errno::ENOENT)
cucumber -- failed
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | calabash-ios-uitest@0.9.1 (exit code: 1)                     | 66 sec   |
+----+--------------------------------------------------------------+----------+
| Issue tracker: ...ithub.com/bitrise-steplib/steps-calabash-ios-uitest/issues |
| Source: https://github.com/bitrise-steplib/steps-calabash-ios-uitest         |
+----+--------------------------------------------------------------+----------+

**Comment by godrei** [comment]
Hi @seansparkman ,
it seens the reported error appears, when features folder is not in the repository root.

May i ask you for some information, how you use calabash with xamarin?
Do you have a features per project types? Where are they located?

Thanks for reporting!

**Comment by seansparkman** [comment]
I am generating a UI Test project.  Maybe I should be using NUnit Test Runner.

**Comment by godrei** [comment]
If you want to run Xamarin.UITest for iOS use our [Xamarin iOS Test step](https://github.com/bitrise-steplib/steps-xamarin-ios-test).

**Comment by mikach** [comment]
Hello! Have the same issue. 
```No such file or directory @ rb_sysopen - features. Please create a features directory to get started. (Errno::ENOENT)```
I don't have `features` folder in root project, I have it in `./cucumber/features`. How can I change working directory to run calabash tests from `cucumber` folder?
